services:
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: always

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
