swagger: "2.0"
info:
  title: Commonplace Go API
  version: 1.0.0
basePath: /api
schemes:
  - http
paths:
  /example:
    get:
      summary: ヘルスチェックエンドポイント
      responses:
        200:
          description: 正常レスポンス
          schema:
            type: string