basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for Commonplace Go API.
  title: Commonplace Go API
  version: "1.0"
paths:
  /example:
    get:
      consumes:
      - application/json
      description: システムの健全性を確認するエンドポイント
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ヘルスチェックエンドポイント
      tags:
      - health
swagger: "2.0"
